#spring.application.name=online-exam-system
#
## MySQL connection
#spring.datasource.url=jdbc:mysql://localhost:3306/exam_system?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Avi@2003
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#spring.jpa.properties.hibernate.definition_definition_override_order=DEFAULT

spring.application.name=online-exam-system

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/exam_system?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Avi@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Fixed Typo (definition_definition_override_order -> definition_override_order)
spring.jpa.properties.hibernate.definition_override_order=DEFAULT